[package]
name = "panopticon-core"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-only"
description = "An extensible data processing and templating engine."
repository = "https://github.com/dolly-parseton/panopticon"
readme = "README.md"
authors = ["dolly-parseton"]
keywords = ["pipeline", "data-processing", "templating", "etl", "polars"]


[features]
default = []
serde = ["dep:serde"]

[dependencies]
thiserror = "2"
serde = { version = "1", features = ["derive"], optional = true }

[[example]]
name = "store_scalars"
path = "examples/extend/store_scalars.rs"

[[example]]
name = "store_collections"
path = "examples/extend/store_collections.rs"

[[example]]
name = "store_nested"
path = "examples/extend/store_nested.rs"

[[example]]
name = "pipeline"
path = "examples/pipeline.rs"

[[example]]
name = "iter_array"
path = "examples/iter_array.rs"

[[example]]
name = "iter_map"
path = "examples/iter_map.rs"

[[example]]
name = "deserialize"
path = "examples/deserialize.rs"
required-features = ["serde"]
